### ISSUE TITLE
SideNav and Navbar

### ISSUE THREAD

**Issue by fjgallard** [fjgallard/blank-slate#7]
- [x] Sidenav should be on top of all elements when shown, including the Navbar
- [x] On sizes sm and lower, hamburger icon should appear, otherwise display the options
- [x] When not logged in, the person icon on the navbar should direct to the login page
- [x] Otherwise, should open a dropdown containing a Logout button.
