### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by fjgallard** [fjgallard/blank-slate#9]
Subissue of #7 

- [x] Contains the list elements "Home", "About", and the person Nav Icon
- [x] Links Properly navigate to their respective pages
- [x] Person icon opens the modal
- [x] Clicking on Blank Slate also navigate to Home
- [x] Toggler when page is sm below, otherwise show the links
